// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')
const service = new chrome.ServiceBuilder('C:\\chromedriver\\chromedriver.exe').build();

describe('paginaprincipaltest', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('paginaprincipaltest', async function() {
    await driver.get("http://localhost:3000/")
    await driver.manage().window().setRect({ width: 1382, height: 736 })
    await driver.findElement(By.css(".producto:nth-child(1) .producto-agregar")).click()
    await driver.findElement(By.css(".producto:nth-child(3) .producto-agregar")).click()
    await driver.findElement(By.css(".producto:nth-child(11) .producto-agregar")).click()
    await driver.findElement(By.css(".producto:nth-child(14) .producto-agregar")).click()
    await driver.findElement(By.css("li:nth-child(2) > .boton-menu")).click()
    await driver.findElement(By.css(".producto:nth-child(2) .producto-agregar")).click()
    await driver.findElement(By.css("li:nth-child(3) > .boton-menu")).click()
    await driver.findElement(By.css(".producto:nth-child(5) .producto-agregar")).click()
    {
      const element = await driver.findElement(By.css(".producto:nth-child(5) .producto-agregar"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    {
      const element = await driver.findElement(By.CSS_SELECTOR, "body")
      await driver.actions({ bridge: true }).moveToElement(element, 0, 0).perform()
    }
    await driver.findElement(By.css("li:nth-child(4) > .boton-menu")).click()
    await driver.findElement(By.css(".producto:nth-child(3) .producto-agregar")).click()
  })
})
