// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')
const service = new chrome.ServiceBuilder('C:\\chromedriver\\chromedriver.exe').build();



describe('testgui', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('testgui', async function() {
    await driver.get("http://localhost:3000/")
    await driver.manage().window().setRect({ width: 1382, height: 736 })
    await driver.findElement(By.css(".producto:nth-child(2) .producto-agregar")).click()
    {
      const element = await driver.findElement(By.css(".producto:nth-child(2) .producto-agregar"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    {
      const element = await driver.findElement(By.CSS_SELECTOR, "body")
      await driver.actions({ bridge: true }).moveToElement(element, 0, 0).perform()
    }
    await driver.findElement(By.css(".producto:nth-child(3) .producto-agregar")).click()
    {
      const element = await driver.findElement(By.css(".producto:nth-child(3) .producto-agregar"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    {
      const element = await driver.findElement(By.CSS_SELECTOR, "body")
      await driver.actions({ bridge: true }).moveToElement(element, 0, 0).perform()
    }
    await driver.findElement(By.css("li:nth-child(2) > .boton-menu")).click()
    await driver.findElement(By.css("li:nth-child(3) > .boton-menu")).click()
    await driver.findElement(By.css("li:nth-child(4) > .boton-menu")).click()
    await driver.findElement(By.css(".producto:nth-child(3) .producto-agregar")).click()
    await driver.findElement(By.css(".boton-carrito")).click()
    await driver.findElement(By.css(".carrito-producto:nth-child(1)")).click()
    await driver.findElement(By.css(".carrito-producto:nth-child(1) .bi")).click()
    await driver.findElement(By.id("carrito-acciones-vaciar")).click()
    await driver.findElement(By.css(".boton-volver")).click()
    {
      const element = await driver.findElement(By.css(".boton-volver"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    {
      const element = await driver.findElement(By.css(".boton-carrito"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    {
      const element = await driver.findElement(By.CSS_SELECTOR, "body")
      await driver.actions({ bridge: true }).moveToElement(element, 0, 0).perform()
    }
    await driver.findElement(By.css(".producto:nth-child(3) .producto-agregar")).click()
    {
      const element = await driver.findElement(By.css(".producto:nth-child(3) .producto-agregar"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    {
      const element = await driver.findElement(By.CSS_SELECTOR, "body")
      await driver.actions({ bridge: true }).moveToElement(element, 0, 0).perform()
    }
    await driver.findElement(By.css(".boton-carrito")).click()
    await driver.findElement(By.id("carrito-acciones-comprar")).click()
    await driver.findElement(By.css(".swal2-confirm")).click()
    await driver.findElement(By.id("email")).click()
    await driver.findElement(By.id("email")).sendKeys("prueba1@gmail.com")
    await driver.findElement(By.id("password")).click()
    await driver.findElement(By.id("password")).sendKeys("12345678")
    await driver.findElement(By.css(".boton-aut")).click()
    await driver.findElement(By.css(".swal2-confirm")).click()
    await driver.findElement(By.css(".boton-aut")).click()
    await driver.findElement(By.css(".swal2-confirm")).click()
    await driver.findElement(By.css("main:nth-child(1)")).click()
    await driver.findElement(By.id("email")).sendKeys("admin@example1.com")
    await driver.findElement(By.css("main:nth-child(1)")).click()
    await driver.findElement(By.css(".boton-aut")).click()
    await driver.findElement(By.css(".swal2-confirm")).click()
    await driver.findElement(By.id("promotion-text")).click()
    await driver.findElement(By.id("promotion-text")).sendKeys("Descuento al 50% en audifonos")
    await driver.findElement(By.id("btn-send-promotion")).click()
    {
      const element = await driver.findElement(By.id("btn-send-promotion"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    {
      const element = await driver.findElement(By.CSS_SELECTOR, "body")
      await driver.actions({ bridge: true }).moveToElement(element, 0, 0).perform()
    }
    await driver.findElement(By.css(".producto-card:nth-child(14) .btn-edit")).click()
    {
      const element = await driver.findElement(By.css(".producto-card:nth-child(14) .btn-edit"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    {
      const element = await driver.findElement(By.CSS_SELECTOR, "body")
      await driver.actions({ bridge: true }).moveToElement(element, 0, 0).perform()
    }
    await driver.findElement(By.id("edit-titulo")).click()
    await driver.findElement(By.id("edit-titulo")).sendKeys("Galaxy Buds2 Pro pro pro")
    await driver.findElement(By.css(".swal2-confirm")).click()
    {
      const element = await driver.findElement(By.css(".swal2-confirm"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    { 
      const element = await driver.findElement(By.CSS_SELECTOR, "body")
      await driver.actions({ bridge: true }).moveToElement(element, 0, 0).perform() 
    }
    await driver.findElement(By.css(".boton-aut")).click()
    {
      const element = await driver.findElement(By.css(".boton-aut"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    {
      const element = await driver.findElement(By.CSS_SELECTOR, "body")
      await driver.actions({ bridge: true }).moveToElement(element, 0, 0).perform()
    }
    await driver.findElement(By.css(".swal2-confirm")).click()
  })
})
