name: Cypress Tests

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Clone Backend Repository
        run: |
          git clone https://github.com/usuario/backend-repo.git backend
          cd backend
          echo "Repositorio del backend clonado con éxito."

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # Configurar y iniciar el backend
      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: Build and Start Backend
        run: |
          cd backend
          ./gradlew bootRun &
          echo "Esperando que el backend inicie..."
          while ! curl -s http://localhost:8084 > /dev/null; do
            sleep 5
          done

      # Configurar y iniciar el frontend
      - name: Install Frontend Dependencies
        run: npm ci

      - name: Create env file
        run: |
          echo "REACT_APP_API_URL=http://localhost:8084" > .env
          echo "BASE_URL=http://localhost:3000" >> .env

      # Ejecutar Cypress
      - name: Run Cypress Tests
        uses: cypress-io/github-action@v6
        with:
          start: npm start
          wait-on: 'http://localhost:3000'
          wait-on-timeout: 120
          browser: chrome
          config: baseUrl=http://localhost:3000

      - name: Upload Cypress artifacts
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: cypress-artifacts
          path: |
            cypress/videos/
            cypress/screenshots/
          retention-days: 7
