name: Cypress Tests

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Dependencies
        run: npm ci

      - name: Start Backend
        run: |
          npm install -g json-server
          json-server --watch db.json --port 8084 &

      - name: Wait for Backend to be Ready
        run: |
          until curl --output /dev/null --silent --head --fail http://localhost:8084; do
            echo "Waiting for backend..."; sleep 5;
          done

      - name: Run Cypress Tests
        uses: cypress-io/github-action@v6
        with:
          start: npm start
          wait-on: 'http://localhost:3000'
