name: Run Selenium Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  selenium-test:
    runs-on: ubuntu-latest

    services:
      selenium:
        image: selenium/standalone-chrome:latest
        options: >-
          --health-cmd="curl --silent --fail http://localhost:4444/wd/hub/status" 
          --health-interval=30s
          --health-timeout=10s
          --health-retries=3
        ports:
          - 4444:4444  # Exponer el puerto de Selenium

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Wait for Selenium to be ready
        run: |
          echo "Esperando a que Selenium esté listo..."
          while ! curl --silent --fail http://localhost:4444/wd/hub/status; do
            echo "Selenium no está listo. Esperando..."
            sleep 5
          done
          echo "Selenium está listo."

      - name: Run Selenium tests
        run: npm run test:selenium
