name: Run Selenium GUI Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  selenium-tests:
    runs-on: ubuntu-latest

    services:
      selenium:
        image: selenium/standalone-chrome
        ports:
          - 4444:4444
        options: >-
          --health-cmd="curl --silent --show-error --fail http://localhost:4444/wd/hub/status"
          --health-timeout=30s
          --health-retries=3

    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Run Selenium tests
        env:
          SELENIUM_REMOTE_URL: http://localhost:4444/wd/hub
        run: |
          npx mocha testGUI/paginaprincipaltest.spec.js
        continue-on-error: true  # Permite que el trabajo continúe aunque las pruebas fallen

      - name: Save test results
        if: failure()
        run: |
          echo "Las pruebas fallaron, guardando resultados..."
          # Puedes guardar logs, screenshots u otros archivos relevantes para depuración
