name: Run Selenium GUI Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  selenium-tests:
    runs-on: ubuntu-latest

    services:
      selenium:
        image: selenium/standalone-chrome
        options: >
          --health-cmd="curl --silent --show-error --fail http://localhost:4444/wd/hub/status" 
          --health-timeout=30s 
          --health-retries=3
          --disable-dev-shm-usage
          --no-sandbox
          --remote-debugging-port=9222

    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: |
          npm install

      - name: Start application
        run: |
          # Inicia tu aplicación en segundo plano
          npm start &  # Esto iniciará la app en segundo plano
          # Espera a que la aplicación esté lista
          sleep 10  # Ajusta el tiempo si es necesario

      - name: Wait for application to be ready
        run: |
          # Asegúrate de que tu aplicación esté lista para recibir solicitudes
          until curl --silent --fail http://localhost:3000; do
            echo "Waiting for application to be ready..."
            sleep 5
          done

      - name: Wait for Selenium service to be ready
        run: |
          # Asegúrate de que Selenium esté disponible antes de ejecutar las pruebas
          until curl --silent --fail http://localhost:4444/wd/hub/status; do
            echo "Waiting for Selenium to be ready..."
            sleep 5
          done

      - name: Run Selenium tests
        run: |
          npx mocha testGUI/paginaprincipaltest.spec.js
