name: Run Selenium GUI Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  selenium-tests:
    runs-on: ubuntu-latest

    services:
      selenium:
        image: selenium/standalone-chrome:latest
        ports:
          - 4444:4444
          - 7900:7900
        options: >-
          --health-cmd "/opt/bin/check-grid.sh"
          --health-interval 10s
          --health-timeout 30s
          --health-retries 5
        volumes:
          - /dev/shm:/dev/shm

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'npm'

      - name: Install dependencies
        run: |
          npm ci || npm install
        env:
          CI: true

      - name: Start application
        run: |
          npm start &
          echo "Esperando a que la aplicación inicie..."
          sleep 15

      - name: Wait for application to be ready
        timeout-minutes: 1
        run: |
          while ! curl -s http://localhost:3000 > /dev/null; do
            sleep 2
            echo "Esperando a que la aplicación esté lista..."
          done

      - name: Wait for Selenium to be ready
        timeout-minutes: 1
        run: |
          while ! curl -s http://localhost:4444/wd/hub/status > /dev/null; do
            sleep 2
            echo "Esperando a que Selenium esté listo..."
          done

      - name: Run Selenium tests
        run: |
          echo "Ejecutando pruebas..."
          npx mocha testGUI/paginaprincipaltest.spec.js --timeout 30000
        env:
          GITHUB_ACTIONS: true
          CI: true

      - name: Upload test artifacts
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: test-results
          path: |
            testGUI/*.log
            screenshots/
            errorShots/
          retention-days: 7